List<Map<String, dynamic>> uniList = [
  {
    'image': 'NU.png',
    'name': 'National University',
    'short': 'NU',
    'cg_image': 'nu_grading.png',
    'id' : 0,
  },
  {
    'image': 'nsu.jpg',
    'name': 'North South University',
    'short': 'NSU',
    'cg_image': 'nsu_grading.jpg',
    'id' : 1,
  },
  {
    'image': 'ewu.png',
    'name': 'East West University',
    'short': 'EWU',
    'cg_image': 'ewu_grading.png',
    'id' : 2,
  },
  {
    'image': 'gub.png',
    'name': 'Green University of Bangladesh',
    'short': 'GUB',
    'cg_image': 'gub_grading.png',
    'id' : 3,
  },
  {
    'image': 'isu.jpg',
    'name': 'nternational Standard University',
    'short': 'ISU',
    'cg_image': 'isu_grading.png',
    'id' : 4,
  },
  {
    'image': 'aust.png',
    'name': 'Ahsanullah University of Science and Technology',
    'short': 'AUST',
    'cg_image': 'aust_grading.png',
    'id' : 5,
  },
  {
    'image': 'aiub.png',
    'name': 'American International University - Bangladesh',
    'short': 'AIUB',
    'cg_image': 'aiub_grading.png',
    'id' : 6,
  },
  {
    'image': 'uiu.png',
    'name': 'United International University',
    'short': 'UIU',
    'cg_image': 'uiu_grading.png',
    'id' : 7,
  },
  {
    'image': 'du.png',
    'name': 'Dhaka University',
    'short': 'DU',
    'cg_image': 'du_grading.png',
    'id' : 8,
  },
  {
    'image': 'sher.png',
    'name': 'Sher-e-Bangla Agricultural University',
    'short': 'SAU',
    'cg_image': 'sher_grading.png',
    'id' : 9,
  },
  {
    'image': 'ulab.jpg',
    'name': 'University of Liberal Arts Bangladesh',
    'short': 'ULAB',
    'cg_image': 'ulab_grading.png',
    'id' : 10,
  },
];